language: node_js
node_js:
- '6'
cache:
  yarn: true
script:
- yarn run lint
notifications:
  slack:
    secure: 3CzNzsJCUhC0yZSuQGRSOLv/X1qWRj1ey+vAVUurwFl13O8Vz/f4kQ241qA1edm26vAAIXxR4N/uVSf1acd6qSi+AaZ/lmAONQ7WUGBWDovtU7P/38IPkPPcMC5Pw/6pSXh5LM6Nwnb46yHAvqNP2Bp471hHRnLScJSTiAkMHCQDAC7VVIGCSuUNpZVJ2/3MgOVpys9CT6Wm5EpwxaEY/ytDyTXv5hOk+WuNydnE52j8k74vpbYaBqLvsnvVjvG+rnDUkKKcml1ptOT0Zaz/CEwSK0MfUviPW8CrfWvhqNm1EHVHeUqnAZt9W1v1N7pmPaIGqTRCwrGdVx24BMcMqqkt4fgLppiuFdz539GJj+S4S3NlwRevviRkTj4bVxNYL5OXp5fr9a+qZ+Rqrq8dvnrHBWsoGq8AMFeBKeb7b6ML356xMekS4TZI3p7er3GSFiPyO6BOxTs6pHoEzGpM7OUkxgb3k8PKJg1+1IpCGVWWOdDXVMVJ9AF0AmxQQDWBwLkAb+kfKFgpl7L/p2XwMyw3C2lQ9LM/QrV2PjMNi4FhV9EU3fg1ZDP80TFYh1ElTIAnCUB7LjAH2gmNWLXOb0h11VjeUqV1TzWWemlicNv3KLx8tSl0yo2vR7TvkImS3ivWTZ8D5uVnWTQL8KIAKrpAvc19QW4CvYtd19Mdz+M=
